/** Reference list of aircraft models available in the Roblox flight sim this airline
 * runs on - used purely as autocomplete suggestions when adding fleet (see
 * AircraftPage.tsx's <datalist>), not a hard enum. The Model field stays free text
 * so a plane missing from this list can still be entered manually. */
export const AIRCRAFT_MODELS = [
  "A-10 Warthog",
  "A6M Zero",
  "Airbus A220",
  "Airbus A320",
  "Airbus A330",
  "Airbus A340",
  "Airbus A350",
  "Airbus A380",
  "Airbus BelugaXL",
  "Airbus H135",
  "Antonov An-22",
  "Antonov AN-225",
  "ATC",
  "ATR-72",
  "Avro Vulcan",
  "B-1 Lancer",
  "B-2 Spirit",
  "B29",
  "Bell 412",
  "Blimp",
  "Boeing 707",
  "Boeing 727",
  "Boeing 737",
  "Boeing 747",
  "Boeing 757",
  "Boeing 767",
  "Boeing 777",
  "Boeing 787",
  "Boeing C-17 Globemaster III",
  "Boeing Dreamlifter",
  "Bombardier CRJ700",
  "Bombardier Learjet",
  "Bombardier Q400",
  "C-130 Hercules",
  "Caproni Stipa",
  "Cessna 172",
  "Cessna 182",
  "Cessna 402",
  "Cessna Caravan",
  "Chinook",
  "Cirrus Vision SF50",
  "Concorde",
  "De Havilland Comet",
  "Derek's Creation",
  "DHC-6 Twin Otter",
  "Diamond DA50",
  "Embraer E190",
  "English Electric Lightning",
  "Eurofighter Typhoon",
  "Extra 300s",
  "F-14 Tomcat",
  "F-15E Strike Eagle",
  "F-16 Fighting Falcon",
  "F-22 Raptor",
  "F-35B",
  "F-4 Phantom",
  "F/A-18 Super Hornet",
  "F4U Corsair",
  "Fokker Dr1",
  "Hawk T1",
  "Hawker Harrier",
  "Hawker Hurricane",
  "Helicopter Particles",
  "Hot Air Balloon",
  "Beechcraft King Air 260",
  "Lockheed L-1011 Tristar",
  "McDonnell Douglas DC-10",
  "McDonnell Douglas MD-11",
  "McDonnell Douglas MD-90",
  "Mig-15",
  "Military UFO",
  "Outfit Picker",
  "P-38 Lightning",
  "P-51 Mustang",
  "Paratrike",
  "Piper Cub",
  "Piper PA-28",
  "Saab JAS 39 Gripen",
  "Santa's Sled",
  "Seaplane Package",
  "Sikorsky S-92",
  "SR-71 Blackbird",
  "Sukhoi Su-27",
  "Sukhoi Su-57",
  "UH-60 Black Hawk",
  "Walrus",
  "Wright Brothers Plane",
] as const;
